/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DropdownItem: typeof import('./../../components/xly-dropdown/dropdown-item.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    RadioGroup: typeof import('./../../components/xly-radio/radio-group.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step: typeof import('./../../components/xly-steps/step.vue')['default']
    TimelineItem: typeof import('./../../components/xly-timeline/timeline-item.vue')['default']
    XlyAvatar: typeof import('./../../components/xly-avatar/index.vue')['default']
    XlyButton: typeof import('./../../components/xly-button/index.vue')['default']
    XlyCard: typeof import('./../../components/xly-card/index.vue')['default']
    XlyCarousel: typeof import('./../../components/xly-carousel/index.vue')['default']
    XlyCascader: typeof import('./../../components/xly-cascader/index.vue')['default']
    XlyChat: typeof import('./../../components/xly-chat/index.vue')['default']
    XlyChatInput: typeof import('./../../components/xly-chat/xly-chat-input.vue')['default']
    XlyChatMessage: typeof import('./../../components/xly-chat/xly-chat-message.vue')['default']
    XlyCol: typeof import('./../../components/xly-col/index.vue')['default']
    XlyDatePicker: typeof import('./../../components/xly-date-picker/index.vue')['default']
    XlyDateRangePicker: typeof import('./../../components/xly-date-range-picker/index.vue')['default']
    XlyDateTimePicker: typeof import('./../../components/xly-date-time-picker/index.vue')['default']
    XlyDateTimeRangePicker: typeof import('./../../components/xly-date-time-range-picker/index.vue')['default']
    XlyDivider: typeof import('./../../components/xly-divider/index.vue')['default']
    XlyDrawer: typeof import('./../../components/xly-drawer/index.vue')['default']
    XlyDropdown: typeof import('./../../components/xly-dropdown/index.vue')['default']
    XlyForm: typeof import('./../../components/xly-form/index.vue')['default']
    XlyFormItem: typeof import('./../../components/xly-form/xly-form-item.vue')['default']
    XlyIcon: typeof import('./../../components/xly-icon/index.vue')['default']
    XlyImage: typeof import('./../../components/xly-image/index.vue')['default']
    XlyInput: typeof import('./../../components/xly-input/index.vue')['default']
    XlyLoading: typeof import('./../../components/xly-loading/index.vue')['default']
    XlyMessage: typeof import('./../../components/xly-message/index.vue')['default']
    XlyModal: typeof import('./../../components/xly-modal/index.vue')['default']
    XlyRadio: typeof import('./../../components/xly-radio/index.vue')['default']
    XlyRate: typeof import('./../../components/xly-rate/index.vue')['default']
    XlyRow: typeof import('./../../components/xly-row/index.vue')['default']
    XlySearchForm: typeof import('./../../components/xly-search-form/index.vue')['default']
    XlySelect: typeof import('./../../components/xly-select/index.vue')['default']
    XlySteps: typeof import('./../../components/xly-steps/index.vue')['default']
    XlyTable: typeof import('./../../components/xly-table/index.vue')['default']
    XlyTabPane: typeof import('./../../components/xly-tabs/xly-tab-pane.vue')['default']
    XlyTabs: typeof import('./../../components/xly-tabs/index.vue')['default']
    XlyTag: typeof import('./../../components/xly-tag/index.vue')['default']
    XlyTimeline: typeof import('./../../components/xly-timeline/index.vue')['default']
    XlyTimePicker: typeof import('./../../components/xly-time-picker/index.vue')['default']
    XlyTimeRangePicker: typeof import('./../../components/xly-time-range-picker/index.vue')['default']
    XlyWatermark: typeof import('./../../components/xly-watermark/index.vue')['default']
  }
}
